version: "3"

services:
  marina:
    image: scarsz/marina
#    build: https://github.com/Scarsz/Marina
    container_name: marina
    environment:
      - TOKEN=${TOKEN}
      - SUPERUSERS=${SUPERUSERS:-95088531931672576}
      - LOGGING_CHANNEL=${LOGGING_CHANNEL}
      - GITHUB_CLIENT=${GITHUB_CLIENT}
      - GITHUB_SECRET=${GITHUB_SECRET}
      - DOCKER_USER=${DOCKER_USER:-root}
      - HTTP_URL=${HTTP_URL}
      - DO_NOT_MENTION_ROLE=${DO_NOT_MENTION_ROLE:-Do not mention}
      - ALLOW_MENTIONS_IN_THANKS=${ALLOW_MENTIONS_IN_THANKS:-true}
    volumes:
      - ./pastes:/bot/pastes
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/${DOCKER_USER:-root}/.docker/config.json:/config.json
    command: --interval 30
    restart: always

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ./data/mongo:/data/db
    restart: always
